// SPDX-License-Identifier: MIT

#include <cstdint>
#include <string>
#include <vector>

#include <cgltf.h>
#include <HandmadeMath.h>
#include <SDL3/SDL.h>
#include <spng.h>

#include <glad/glad.h>


#define ARRLEN(arr) (sizeof(arr) / sizeof((arr)[0]))

#define DIE(...) std::fprintf(stderr, "ERR: " __VA_ARGS__); std::fprintf(stderr, "\n"); std::fflush(stderr); *(volatile int*)0x0 = 1234;
#define LOG(...) std::fprintf(stdout, "MSG: " __VA_ARGS__); std::fprintf(stdout, "\n"); std::fflush(stdout);

#define ASSERT(cond)                                                    \
    do {                                                                \
        if (!(cond)) {                                                  \
            DIE("ASSERT FAILED %s:%d: %s", __FILE__, __LINE__, #cond);  \
        }                                                               \
    } while (0);                                                        \

#define MODEL_FOLDER    "common/glTF/"
#define MODEL_PATH      MODEL_FOLDER "/FlightHelmet.gltf"

struct Vertex_1P1N1T {
    HMM_Vec3 p;
    HMM_Vec3 n;
    HMM_Vec2 t;
};

struct Primitive {
    GLuint vao;
    GLuint vbo;
    GLuint ibo;
    size_t indices;
    size_t texture_idx;
};

struct Model {
    std::vector<Primitive>  primitives;
    HMM_Mat4                transform;
};

struct Texture {
    GLuint tex;
};

// Helper: Get human-readable glGetError enum
static const char* gl_error_string(GLenum err) {
    switch (err) {
        case GL_INVALID_ENUM:                   return "GL_INVALID_ENUM";
        case GL_INVALID_VALUE:                  return "GL_INVALID_VALUE";
        case GL_INVALID_OPERATION:              return "GL_INVALID_OPERATION";
        case GL_INVALID_FRAMEBUFFER_OPERATION:  return "GL_INVALID_FRAMEBUFFER_OPERATION";
        case GL_OUT_OF_MEMORY:                  return "GL_OUT_OF_MEMORY";
        default: ASSERT(0); return NULL;
    }
}

// Helper: Check for errors generated by OpenGL API call
static void gl_check_error(const char* code, const char* file, unsigned int line) {
    const GLenum error = glGetError();
    if (error != GL_NO_ERROR) {
        DIE("%s:%u: %s FAILED (glGetError() = %s)", file, line, code, gl_error_string(error));
    }
}
#define GLCHECK(code) code; gl_check_error(#code, __FILE__, __LINE__);

int main(int argc, char* argv[]) {
    // Initialize SDL
    if (!SDL_Init(SDL_INIT_VIDEO | SDL_INIT_EVENTS)) {
        DIE("Failed to initialize SDL: %s", SDL_GetError());
    }

    // Create application window
    constexpr Uint32 WNDFLAGS = SDL_WINDOW_RESIZABLE | SDL_WINDOW_OPENGL;
    SDL_Window* wnd = SDL_CreateWindow(__FILE__, 1280, 720, WNDFLAGS);
    if (!wnd) {
        DIE("Failed to create SDL window: %s", SDL_GetError());
    }

    // Create OpenGL 3.3 (core) window context
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 3);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_CORE);
    SDL_GLContext wgl = SDL_GL_CreateContext(wnd);
    if (!wgl) {
        DIE("Failed to create window OpenGL context: %s", SDL_GetError());
    }
    SDL_GL_MakeCurrent(wnd, wgl);

    // Load OpenGL functions
    if (!gladLoadGLLoader((GLADloadproc)SDL_GL_GetProcAddress)) {
        DIE("Failed to load OpenGL functions");
    }

    LOG("GL_VERSION:    %s", glGetString(GL_VERSION));
    LOG("GL_VENDOR:     %s", glGetString(GL_VENDOR));
    LOG("GL_RENDERER:   %s", glGetString(GL_RENDERER));

    // Load glTF scene
    cgltf_data* gltf = { };
    cgltf_options options = { };
    if (cgltf_parse_file(&options, MODEL_PATH, &gltf) != cgltf_result_success) {
        DIE("Failed to parse glTF file " MODEL_PATH);
    }
    if (cgltf_load_buffers(&options, gltf, MODEL_PATH) != cgltf_result_success) {
        DIE("Failed to load glTF buffers");
    }

    // Upload scene to GPU
    std::vector<Model> scene = { }; scene.resize(gltf->meshes_count);
    for (size_t i = 0; i < gltf->meshes_count; ++i) {
        Model* model = &scene[i];
        model->primitives.resize(gltf->meshes[i].primitives_count);
        for (size_t j = 0; j < gltf->meshes[i].primitives_count; ++j) {
            Primitive* prim                 = &model->primitives[j];
            const cgltf_primitive* gprim    = &gltf->meshes[i].primitives[j];

            // Need position, normal, and texcoord vertex attributes
            const cgltf_attribute* gattr_p = NULL;
            const cgltf_attribute* gattr_n = NULL;
            const cgltf_attribute* gattr_t = NULL;
            for (size_t k = 0; k < gprim->attributes_count; ++k) {
                const cgltf_attribute* gattr = &gprim->attributes[k];
                switch (gattr->type) {
                    case cgltf_attribute_type_position: { gattr_p = gattr; } break;
                    case cgltf_attribute_type_normal:   { gattr_n = gattr; } break;
                    case cgltf_attribute_type_texcoord: { gattr_t = gattr; } break;
                    default: break;
                };
            }
            if (!gattr_p || !gattr_n || !gattr_t) {
                DIE("glTF model is missing one or more required vertex attributes");
            }
            if (gattr_p->data->count != gattr_n->data->count || gattr_n->data->count != gattr_t->data->count) {
                DIE("glTF model vertex attribute data size mismatch");
            }
            const size_t vertex_count = gattr_p->data->count;

            // Vertex array objects store vertex layout and buffer references
            GLCHECK(glGenVertexArrays(1, &prim->vao));
            GLCHECK(glBindVertexArray(prim->vao));

            // These buffers are generic and can store anything. This one stores vertex data
            GLCHECK(glGenBuffers(1, &prim->vbo));
            GLCHECK(glBindBuffer(GL_ARRAY_BUFFER, prim->vbo));

            // This call can be used to upload data but we instead pass NULL to pre-allocate the buffer
            GLCHECK(glBufferData(GL_ARRAY_BUFFER, sizeof(Vertex_1P1N1T) * vertex_count, NULL, GL_STATIC_DRAW));

            // glMapBuffer maps the GPU buffer into memory so we can write to it directly instead of having to
            // allocate a temporary buffer and copy it with glBufferData
            Vertex_1P1N1T* vertices = (Vertex_1P1N1T*)GLCHECK(glMapBuffer(GL_ARRAY_BUFFER, GL_WRITE_ONLY));
            for (size_t k = 0; k < vertex_count; ++k) {
                // position
                cgltf_accessor_read_float(gattr_p->data, k, vertices[k].p.Elements, 3);
                // normal
                cgltf_accessor_read_float(gattr_n->data, k, vertices[k].n.Elements, 3);
                // texcoord
                cgltf_accessor_read_float(gattr_t->data, k, vertices[k].t.Elements, 2);
            }
            GLCHECK(glUnmapBuffer(GL_ARRAY_BUFFER));

            // Upload index data to buffer
            GLCHECK(glGenBuffers(1, &prim->ibo));
            GLCHECK(glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, prim->ibo));
            GLCHECK(glBufferData(GL_ELEMENT_ARRAY_BUFFER, sizeof(unsigned int) * gprim->indices->count, NULL, GL_STATIC_DRAW));
            unsigned int* indices = (unsigned int*)GLCHECK(glMapBuffer(GL_ELEMENT_ARRAY_BUFFER, GL_WRITE_ONLY));
            for (size_t k = 0; k < gprim->indices->count; ++k) {
                cgltf_accessor_read_uint(gprim->indices, k, &indices[k], 1);
            }
            GLCHECK(glUnmapBuffer(GL_ELEMENT_ARRAY_BUFFER));

            // Set buffer layout
            // V3 position
            GLCHECK(glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, sizeof(Vertex_1P1N1T), (void*)offsetof(Vertex_1P1N1T, p)));
            GLCHECK(glEnableVertexAttribArray(0));
            // V3 normal
            GLCHECK(glVertexAttribPointer(1, 3, GL_FLOAT, GL_FALSE, sizeof(Vertex_1P1N1T), (void*)offsetof(Vertex_1P1N1T, n)));
            GLCHECK(glEnableVertexAttribArray(1));
            // V2 texcoord
            GLCHECK(glVertexAttribPointer(2, 2, GL_FLOAT, GL_FALSE, sizeof(Vertex_1P1N1T), (void*)offsetof(Vertex_1P1N1T, t)));
            GLCHECK(glEnableVertexAttribArray(2));

            // Future draw calls need to know the number of indices
            prim->indices = gprim->indices->count;

            // Store texture index
            cgltf_texture* texture = gprim->material->pbr_metallic_roughness.base_color_texture.texture; ASSERT(texture);
            prim->texture_idx = texture - gltf->textures;
            ASSERT(prim->texture_idx < gltf->textures_count);
        }
    }

    // Store model transformation
    for (size_t i = 0; i < gltf->nodes_count; ++i) {
        cgltf_node* node = &gltf->nodes[i];
        if (!node->mesh) {
            continue;
        }
        const size_t model_index = node->mesh - gltf->meshes; ASSERT(model_index < scene.size());
        cgltf_node_transform_world(node, scene[model_index].transform.Elements[0]);
    }

    // Upload images
    std::vector<Texture> textures = { }; textures.resize(gltf->textures_count);
    for (size_t i = 0; i < gltf->textures_count; ++i) {
        // Fix relative image path
        if (!gltf->textures[i].image->uri) {
            DIE("glTF texture has NULL URI");
        }
        char texture_path[1024] = { };
        std::snprintf(texture_path, sizeof(texture_path), MODEL_FOLDER "/%s", gltf->textures[i].image->uri);

        // Load image file
        std::FILE* f = std::fopen(texture_path, "rb");
        if (!f) {
            DIE("Failed to open image file %s", texture_path);
        }
        std::vector<uint8_t> bytes = { };
        std::fseek(f, 0, SEEK_END);
        bytes.resize(std::ftell(f));
        std::fseek(f, 0, SEEK_SET);
        std::fread(&bytes[0], sizeof(uint8_t), bytes.size(), f);
        std::fclose(f);

        // Parse PNG (RGBA8)
        spng_ctx* spng = spng_ctx_new(0); ASSERT(spng);
        spng_set_png_buffer(spng, &bytes[0], bytes.size());
        spng_ihdr hdr = { };
        if (spng_get_ihdr(spng, &hdr)) {
            DIE("Image %s is not a PNG file", texture_path);
        }
        std::vector<uint32_t> pixels = { }; pixels.resize(hdr.width * hdr.height);
        int decode_response = spng_decode_image(spng, &pixels[0], pixels.size() * sizeof(uint32_t), SPNG_FMT_RGBA8, 0);
        if (decode_response != 0) {
            DIE("Error while decoding PNG image %s: %s", texture_path, spng_strerror(decode_response));
        }
        spng_ctx_free(spng);

        // Upload to GPU
        GLCHECK(glGenTextures(1, &textures[i].tex));
        GLCHECK(glBindTexture(GL_TEXTURE_2D, textures[i].tex));
        GLCHECK(glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA8, hdr.width, hdr.height, 0, GL_RGBA, GL_UNSIGNED_BYTE, &pixels[0]));
        GLCHECK(glGenerateMipmap(GL_TEXTURE_2D));

        LOG("[%02lu/%02lu] Loaded texture %s", (unsigned long)i+1, (unsigned long)gltf->textures_count, texture_path);
    }

    // Create OpenGL program object
    GLuint prog = GLCHECK(glCreateProgram());

    // Compile OpenGL shaders
    struct ShaderDef {
        const char* path;
        GLenum      type;
    };
    const ShaderDef SHADERS[] = {
        { "graphics/opengl/gltf_vs.glsl", GL_VERTEX_SHADER },
        { "graphics/opengl/gltf_fs.glsl", GL_FRAGMENT_SHADER },
    };
    for (size_t i = 0; i < ARRLEN(SHADERS); ++i) {
        // Load shader source as text
        std::FILE* f = std::fopen(SHADERS[i].path, "r");
        if (!f) {
            DIE("Failed to open shader file %s", SHADERS[i].path);
        }
        std::fseek(f, 0, SEEK_END);
        const long flen = std::ftell(f);
        std::fseek(f, 0, SEEK_SET);
        std::string source(flen, '\0');
        std::fread(&source[0], sizeof(char), flen, f);
        std::fclose(f);

        // Create shader object
        GLuint shader = GLCHECK(glCreateShader(SHADERS[i].type));

        // Upload shader source
        const char* source_c_str = source.c_str();
        GLCHECK(glShaderSource(shader, 1, &source_c_str, NULL));

        // Compile shader and check compile status
        GLCHECK(glCompileShader(shader));
        GLint status = 0; GLCHECK(glGetShaderiv(shader, GL_COMPILE_STATUS, &status));
        if (!status) {
            char error[512] = { }; GLCHECK(glGetShaderInfoLog(shader, sizeof(error), NULL, error));
            DIE("Failed to compile shader %s:\n%s", SHADERS[i].path, error);
        }
        LOG("[%02lu/%02lu] Compiled shader %s", (unsigned long)i+1, ARRLEN(SHADERS), SHADERS[i].path);

        // Attach shader stage to render program
        GLCHECK(glAttachShader(prog, shader))
    }

    // Link program and check link status
    GLCHECK(glLinkProgram(prog));
    GLint status = 0; GLCHECK(glGetProgramiv(prog, GL_LINK_STATUS, &status));
    if (!status) {
        char error[512] = { }; GLCHECK(glGetProgramInfoLog(prog, sizeof(error), NULL, error));
        DIE("Failed to link program:\n%s", error);
    }

    // Set OpenGL state for rendering
    GLCHECK(glUseProgram(prog));        // Render using our shaders
    GLCHECK(glEnable(GL_DEPTH_TEST));   // Enable z-buffer test

    // Window loop
    bool running = true;
    do {
        // Poll events
        SDL_Event evt = { };
        while (SDL_PollEvent(&evt)) {
            switch (evt.type) {
                case SDL_EVENT_QUIT: {
                    running = false;
                } break;
                case SDL_EVENT_KEY_DOWN: {
                    if (evt.key.key == SDLK_ESCAPE) {
                        running = false;
                    }
                } break;
            }
        }

        // Application time in seconds
        const float now = (float)SDL_GetTicks() / 1e3f;

        // Update viewport dimensions
        int vp_w = 0; int vp_h = 0;
        SDL_GetWindowSizeInPixels(wnd, &vp_w, &vp_h);
        GLCHECK(glViewport(0, 0, vp_w, vp_h));

        // Update camera
        HMM_Vec3 cam = HMM_V3(HMM_SinF(now), 0.3f, HMM_CosF(now));

        // Update view matrix
        // Camera matrix
        HMM_Mat4 vp_cam = HMM_LookAt_RH(cam, HMM_V3(0.0f, 0.3f, 0.0f), HMM_V3(0.0f, 1.0f, 0.0f));
        // Perspective projection matrix
        HMM_Mat4 vp_proj = HMM_Perspective_RH_NO(HMM_ToRad(90.0f / 2.0f), (float)vp_w / (float)vp_h, 0.1f, 10.0f);
        // Combine camera + projection
        HMM_Mat4 vp = HMM_Mul(vp_proj, vp_cam);
        GLCHECK(glUniformMatrix4fv(glGetUniformLocation(prog, "u_view"), 1, GL_FALSE, vp.Elements[0]));

        // Update texture sampler (always 0)
        GLCHECK(glUniform1i(glGetUniformLocation(prog, "u_texture"), 0));

        // Clear the framebuffer (both color and depth attachments)
        GLCHECK(glClearColor(0.1f, 0.1f, 0.1f, 1.0f));
        GLCHECK(glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT));

        // Render scene
        for (Model& model : scene) {
            // Update model transformation
            GLCHECK(glUniformMatrix4fv(glGetUniformLocation(prog, "u_model"), 1, GL_FALSE, model.transform.Elements[0]));

            // Render primitives
            for (Primitive& prim : model.primitives) {
                // Restore buffer bindings
                GLCHECK(glBindVertexArray(prim.vao));

                // Bind texture
                GLCHECK(glActiveTexture(GL_TEXTURE0));
                GLCHECK(glBindTexture(GL_TEXTURE_2D, textures[prim.texture_idx].tex));

                // Draw indexed triangles
                GLCHECK(glDrawElements(GL_TRIANGLES, prim.indices, GL_UNSIGNED_INT, NULL));
            }
        }

        // Swap the front and back window buffers
        SDL_GL_SwapWindow(wnd);
    } while (running);

    SDL_DestroyWindow(wnd);
    SDL_Quit();

    return 0;
}
